### ISSUE TITLE
Webcam does not play

### ISSUE THREAD

**Issue by Sean-Zeo** [nkien0204/webrtc-ffmpeg#1]
Hi, the webcam doesn't appear to display upon testing (and changing the webcam name to the exact requirement).
![image](https://user-images.githubusercontent.com/127526527/227774168-32de6586-3106-4d3c-8df4-f1dd98c12c70.png)

Any thoughts?

Thanks sir. :)

ffmpeg.exe is placed into the project root also.

**Comment by nkien0204** [comment]
Hello Sean, can you show me the log? Thanks

**Comment by Sean-Zeo** [comment]
Hi friend, looking at the log it appears this is the following issue;
`{"level":"ERROR","ts":"2023-03-27 14:47:41","file":"webrtc-ffmpeg/manage_streams.go:159","msg":"RunCommand failed","error":"exec: \"ffmpeg\": cannot run executable found relative to current directory"}`

I have placed ffmpeg in both the root folder and also as an additional folder in the root of the project (known as ffmpeg).
However this issue occurs.

![image](https://user-images.githubusercontent.com/127526527/227960613-a02f0c36-da48-4015-8168-48eb5a886405.png)

**Comment by nkien0204** [comment]
this error show that you are not in the same directory with project. So can you check that again, cd to the project and run "main serve wf". It's better if you can give a short video!!

**Comment by Sean-Zeo** [comment]
Hi, I've needed to use 'lets-go' instead of 'main', ffmpeg is in the exact same folder as the go project

**Comment by nkien0204** [comment]
I still don't get your point=))
Do you have Telegram or Skype, we can discuss more about that!

**Comment by Sean-Zeo** [comment]
Hi sir, I can send you the video via discord or email, whichever suits best.  Thanks! :)

**Comment by nkien0204** [comment]
this is my Discord tag nkien0204#6324. Thanks

**Comment by Sean-Zeo** [comment]
Resolved by changing 
![image](https://user-images.githubusercontent.com/127526527/227995791-5816f3a5-0637-4309-a777-2d4281914d7f.png)
